ServerEvents.recipes((event) => {
    // 添加配方
    // create:sequenced_assembly
    // 添加 rainbowcompound:strange_colored_ingot 的配方
    event.recipes.create
        .sequenced_assembly(
            ["rainbowcompound:strange_colored_ingot"],
            "gtceu:brass_ingot",
            [
                event.recipes.create.deploying(
                    "rainbowcompound:strange_colored_ingot",
                    [
                        "rainbowcompound:strange_colored_ingot",
                        "rainbowcompound:netherwartite_ingot",
                    ],
                ),
                event.recipes.create.deploying(
                    "rainbowcompound:strange_colored_ingot",
                    [
                        "rainbowcompound:strange_colored_ingot",
                        "rainbowcompound:blazeite_ingot",
                    ],
                ),
                event.recipes.create.deploying(
                    "rainbowcompound:strange_colored_ingot",
                    [
                        "rainbowcompound:strange_colored_ingot",
                        "rainbowcompound:glowstoneite_ingot",
                    ],
                ),
                event.recipes.create.deploying(
                    "rainbowcompound:strange_colored_ingot",
                    [
                        "rainbowcompound:strange_colored_ingot",
                        "rainbowcompound:slimeite_ingot",
                    ],
                ),
                event.recipes.create.deploying(
                    "rainbowcompound:strange_colored_ingot",
                    [
                        "rainbowcompound:strange_colored_ingot",
                        "rainbowcompound:warpedite_ingot",
                    ],
                ),
                event.recipes.create.deploying(
                    "rainbowcompound:strange_colored_ingot",
                    [
                        "rainbowcompound:strange_colored_ingot",
                        "rainbowcompound:enderite_ingot",
                    ],
                ),
                event.recipes.create.deploying(
                    "rainbowcompound:strange_colored_ingot",
                    [
                        "rainbowcompound:strange_colored_ingot",
                        "rainbowcompound:frostite_ingot",
                    ],
                ),
                event.recipes.create.deploying(
                    "rainbowcompound:strange_colored_ingot",
                    [
                        "rainbowcompound:strange_colored_ingot",
                        "rainbowcompound:chorusite_ingot",
                    ],
                ),
            ],
        )
        .transitionalItem("rainbowcompound:strange_colored_ingot")
        .loops(1);
});
