#if ture, you have to use preferred tool to harvest blocks. (default: false)
"require preferred tool" = false
#if ture, you can allways break insta-breakable blocks. (default: true)
"allways allow insta-break" = true
#if ture, you have to use tool to break blocks in creative mode. (default: false)
"force in creative" = false

