
[light_sources]
	entities = true
	self = true
	block_entities = true
	water_sensitive_check = true

	[light_sources.settings]

		[light_sources.settings.entities]

			[light_sources.settings.entities.minecraft]
				player = true
				item = true
				bee = true
				pig = true
				lightning_bolt = true
				zombie = true
				skeleton = true
				witch = true
				wither_skeleton = true
				experience_orb = true
				arrow = true
				potion = true
				wandering_trader = true
				trader_llama = true
				item_frame = true

			[light_sources.settings.entities.create]
				stationary_contraption = true

			[light_sources.settings.entities.mythicbotany]
				alf_pixie = true

			[light_sources.settings.entities.productivebees]
				configurable_bee = true
				ashy_mining_bee = true

			[light_sources.settings.entities.botanicpledge]
				yggdrasil_guardian = true
				yggdrasil_warden = true
				yggd_focus = true

			[light_sources.settings.entities.botania]
				magic_missile = true
				pixie = true
				magic_landmine = true
				mana_burst = true

			[light_sources.settings.entities.corpse]
				corpse = true

